title: Translation Project

logo: /assets/collaborativetranslationlogo.png

description: Email received on March 12, 2019 10:00 AM

show_downloads: false

google_analytics:

theme: jekyll-theme-minimal
